# Generated by Django 5.0.6 on 2024-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_hotelimages_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='room_count',
            field=models.IntegerField(default=10),
        ),
    ]
